import os
import json
import logging
import asyncio
import datetime
from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles

from backend.app.database import init_db, SessionLocal
from backend.app import models
from backend.app.routes import auth, cameras, events, alerts, zones, anpr, analytics, watchlist, system, stream
from ai.event_engine import AnalyticsEventEngine

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(name)s: %(message)s")
logger = logging.getLogger("EdgeEye.Main")

app = FastAPI(
    title="EdgeEye — Intelligent Border Video Analytics Platform",
    description="Software-Defined AI-powered CCTV Video Analytics for Border and Security Surveillance",
    version="1.0.0"
)

# Enable CORS for frontend integration
cors_env = os.getenv("CORS_ORIGINS", "*")
if cors_env.strip() == "*":
    origins = ["*"]
else:
    origins = [orig.strip() for orig in cors_env.split(",") if orig.strip()]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Evidence static files
EVIDENCE_DIR = os.getenv("EVIDENCE_DIR") or os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "evidence"))
os.makedirs(EVIDENCE_DIR, exist_ok=True)
app.mount("/evidence", StaticFiles(directory=EVIDENCE_DIR), name="evidence")

# Global event engine
global_engine = AnalyticsEventEngine(SessionLocal)
stream.set_global_engine(global_engine)
system.set_global_engine(global_engine)

# Active WebSocket clients
connected_clients: list[WebSocket] = []

@app.websocket("/ws/alerts")
async def websocket_alerts_endpoint(websocket: WebSocket):
    await websocket.accept()
    connected_clients.append(websocket)
    logger.info(f"WebSocket client connected. Total clients: {len(connected_clients)}")
    try:
        # Send recent alerts on initial connect
        for a in global_engine.recent_alerts[:5]:
            await websocket.send_text(json.dumps(a))

        while True:
            # Keep-alive receive
            data = await websocket.receive_text()
            if data == "ping":
                await websocket.send_text("pong")
    except WebSocketDisconnect:
        connected_clients.remove(websocket)
        logger.info("WebSocket client disconnected.")
    except Exception as e:
        if websocket in connected_clients:
            connected_clients.remove(websocket)
        logger.error(f"WebSocket error: {e}")

async def background_alert_broadcast():
    """
    Periodically checks if new alerts were generated by the event engine and broadcasts to WebSockets.
    """
    last_sent_alert_id = 0
    while True:
        try:
            if connected_clients and global_engine.recent_alerts:
                latest = global_engine.recent_alerts[0]
                if latest.get("id") != last_sent_alert_id:
                    last_sent_alert_id = latest.get("id")
                    payload = json.dumps(latest)
                    for ws in list(connected_clients):
                        try:
                            await ws.send_text(payload)
                        except Exception:
                            if ws in connected_clients:
                                connected_clients.remove(ws)
        except Exception as e:
            logger.error(f"Broadcast error: {e}")
        await asyncio.sleep(1.0)

def seed_demo_data():
    db = SessionLocal()
    try:
        # Seed Cameras
        if db.query(models.Camera).count() == 0:
            logger.info("Seeding initial border security cameras...")
            cameras_data = [
                models.Camera(
                    id="BOP-01",
                    name="Sector Alpha — Forward Perimeter",
                    location="Sector Alpha",
                    source_type="DEMO_VIDEO",
                    status="ONLINE",
                    fps=25,
                    resolution="1920x1080",
                    is_active=True
                ),
                models.Camera(
                    id="BOP-02",
                    name="Sector Bravo — Riverine Bed",
                    location="Sector Bravo",
                    source_type="DEMO_VIDEO",
                    status="ONLINE",
                    fps=25,
                    resolution="1920x1080",
                    is_active=True
                ),
                models.Camera(
                    id="BOP-03",
                    name="Sector Charlie — High Ridge Post",
                    location="Sector Charlie",
                    source_type="DEMO_VIDEO",
                    status="ONLINE",
                    fps=25,
                    resolution="1920x1080",
                    is_active=True
                ),
                models.Camera(
                    id="CHECKPOST-01",
                    name="Main Transit Checkpost & Gate",
                    location="Main Gate",
                    source_type="DEMO_VIDEO",
                    status="ONLINE",
                    fps=30,
                    resolution="1920x1080",
                    is_active=True
                )
            ]
            db.add_all(cameras_data)
            db.commit()

        # Seed Virtual Fence Zones
        if db.query(models.Zone).count() == 0:
            logger.info("Seeding border virtual fence zones...")
            zones_data = [
                models.Zone(
                    camera_id="BOP-01",
                    name="Red Line Restricted Zone",
                    zone_type="RESTRICTED",
                    coordinates="[[150, 420], [800, 420], [800, 560], [150, 560]]",
                    severity="CRITICAL",
                    enabled=True
                ),
                models.Zone(
                    camera_id="BOP-02",
                    name="Riverbed Crossing Buffer",
                    zone_type="PERIMETER",
                    coordinates="[[100, 380], [600, 380], [600, 520], [100, 520]]",
                    severity="HIGH",
                    enabled=True
                ),
                models.Zone(
                    camera_id="CHECKPOST-01",
                    name="Entry Gate Security Barrier",
                    zone_type="RESTRICTED",
                    coordinates="[[300, 480], [950, 480], [950, 650], [300, 650]]",
                    severity="HIGH",
                    enabled=True
                )
            ]
            db.add_all(zones_data)
            db.commit()

        # Seed Watchlist
        if db.query(models.Watchlist).count() == 0:
            logger.info("Seeding border watchlist records...")
            watchlist_data = [
                models.Watchlist(
                    plate_number="DEMO-001",
                    reason="Flagged for unauthorized border approach",
                    severity="CRITICAL",
                    description="White SUV associated with illicit contraband surveillance."
                ),
                models.Watchlist(
                    plate_number="DEMO-4821",
                    reason="Suspicious multi-sector movement",
                    severity="CRITICAL",
                    description="Reported scout vehicle observed near unpatrolled terrain."
                ),
                models.Watchlist(
                    plate_number="PB-10-AZ-9988",
                    reason="Stolen commercial transport alert",
                    severity="HIGH",
                    description="Heavy cargo vehicle missing commercial transit clearance."
                )
            ]
            db.add_all(watchlist_data)
            db.commit()

        # Seed sample plates
        if db.query(models.Plate).count() == 0:
            sample_plates = [
                models.Plate(
                    plate_number="DEMO-4821",
                    vehicle_type="Car",
                    camera_id="CHECKPOST-01",
                    timestamp=datetime.datetime.utcnow() - datetime.timedelta(minutes=15),
                    confidence=0.96,
                    status="WATCHLIST"
                ),
                models.Plate(
                    plate_number="DL-01-AB-1234",
                    vehicle_type="Truck",
                    camera_id="CHECKPOST-01",
                    timestamp=datetime.datetime.utcnow() - datetime.timedelta(minutes=32),
                    confidence=0.93,
                    status="AUTHORIZED"
                ),
                models.Plate(
                    plate_number="DEMO-001",
                    vehicle_type="SUV",
                    camera_id="CHECKPOST-01",
                    timestamp=datetime.datetime.utcnow() - datetime.timedelta(hours=1),
                    confidence=0.98,
                    status="WATCHLIST"
                )
            ]
            db.add_all(sample_plates)
            db.commit()

        # Seed sample alerts
        if db.query(models.Alert).count() == 0:
            ev1 = models.Event(
                camera_id="BOP-01",
                event_type="INTRUSION",
                object_id="Person #17",
                timestamp=datetime.datetime.utcnow() - datetime.timedelta(minutes=8),
                confidence=0.94,
                severity="CRITICAL",
                status="NEW",
                metadata_json='{"rule": "Red Line Restricted Zone", "dwell": "14s"}'
            )
            db.add(ev1)
            db.flush()

            al1 = models.Alert(
                event_id=ev1.id,
                camera_id="BOP-01",
                title="Perimeter Intrusion Detected — BOP-01",
                message="Person #17 breached Red Line Restricted Zone.",
                severity="CRITICAL",
                status="UNACKNOWLEDGED",
                created_at=datetime.datetime.utcnow() - datetime.timedelta(minutes=8)
            )
            db.add(al1)

            ev2 = models.Event(
                camera_id="CHECKPOST-01",
                event_type="WATCHLIST_MATCH",
                object_id="Plate DEMO-4821",
                timestamp=datetime.datetime.utcnow() - datetime.timedelta(minutes=15),
                confidence=0.96,
                severity="CRITICAL",
                status="NEW",
                metadata_json='{"plate": "DEMO-4821", "reason": "Suspicious multi-sector movement"}'
            )
            db.add(ev2)
            db.flush()

            al2 = models.Alert(
                event_id=ev2.id,
                camera_id="CHECKPOST-01",
                title="Watchlist Vehicle Identified — CHECKPOST-01",
                message="Vehicle with plate DEMO-4821 matched border alert list.",
                severity="CRITICAL",
                status="UNACKNOWLEDGED",
                created_at=datetime.datetime.utcnow() - datetime.timedelta(minutes=15)
            )
            db.add(al2)
            db.commit()

    except Exception as e:
        logger.error(f"Error seeding demo data: {e}")
        db.rollback()
    finally:
        db.close()

@app.on_event("startup")
async def startup_event():
    init_db()
    seed_demo_data()
    global_engine.sync_zones_from_db()
    # Register default cameras into processor
    for cid in ["BOP-01", "BOP-02", "BOP-03", "CHECKPOST-01"]:
        global_engine.register_camera(cid)
    # Start background alert broadcasting task
    asyncio.create_task(background_alert_broadcast())
    logger.info("EdgeEye AI & Video Analytics System initialized successfully.")

@app.on_event("shutdown")
async def shutdown_event():
    logger.info("Releasing EdgeEye video streams and background workers...")
    global_engine.cleanup()

# Mount routers
app.include_router(auth.router)
app.include_router(cameras.router)
app.include_router(events.router)
app.include_router(alerts.router)
app.include_router(zones.router)
app.include_router(anpr.router)
app.include_router(analytics.router)
app.include_router(watchlist.router)
app.include_router(system.router)
app.include_router(stream.router)
